### ISSUE TITLE
openstack ceilometer collector in verision 3.0

### ISSUE THREAD

**Issue by MuhammedSaqib** [icclab/cyclops#12]
Hi,
I am unable to find openstack ceilometer collector in cyclops v3.0. In v2.1 it is available under "cyclops/collectors/openstack-ceilometer/" directory, however in v3.0 there isn't.
Also please tell me the current stable release of cyclops.

Thank you,
Saqib

**Comment by ManuPerezBelmonte** [comment]
Hi Saquib, 

We are working on the update right now, It should be out in a couple of weeks max. 

Will close this issue as soon as we release it.

Cheers!

**Comment by ManuPerezBelmonte** [comment]
The 3.0 version has been released at e666f46

let us know if you have any other doubt,

Cyclops Team

**Comment by saqibarfeen** [comment]
Hello Belmonte
I am also unable to find cyclops-dashboard. Is it present in v3.0?

Saqib
