### ISSUE TITLE
Any Dashboard for this version?!

### ISSUE THREAD

**Issue by Sabousian** [icclab/cyclops#2]
hi,

I'm gonna install cyclops and i'm afraid if there is any dashboard for this version,
please guide me how to have a dashboard for this version of cyclops,

Thanks

**Comment by ManuPerezBelmonte** [comment]
Hi Sabousian, 

At the moment there is no dashboard support for Cyclops 2.0. We are currently working on a renewed and more usable dashboard which will be released as soon as it supports the basic functionalities of the framework.

The release will be announced on our blog https://blog.zhaw.ch/icclab/ and also in our Twitter https://twitter.com/rcb_cyclops

Cyclops Team.

**Comment by ManuPerezBelmonte** [comment]
Sabousian, 

We just released the first version of Dashboard 2.0, make sure you give it a try.

https://github.com/icclab/cyclops-dashboard

Let us know if you have any trouble and if you could deploy it without trouble.

Cyclops Team.
