### ISSUE TITLE
Ceilometer Collector Config

### ISSUE THREAD

**Issue by Sabousian** [icclab/cyclops#4]
There is a mistype in openstack collector that will cause problem

PublisherBroadcastExchange=**cylops**.ceilometer.collector.broadcast

the problem is that **cyclops** is mistyped and it will created another broadcast exchange that the udr system will not listen so it does not collect any data.

**Comment by ManuPerezBelmonte** [comment]
Hi Sabousian,

Thanks for pointing the error. We will fix it immediately :)

Cyclops Team.

2016-08-21 21:37 GMT+02:00 Sabousian <notifications@github.com>:
